"""initial schema

Revision ID: 1c4b2566b9cd
Revises: 
Create Date: 2026-08-22 13:26:38.396024

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c4b2566b9cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """PostgreSQL is canonical: ensure pgvector exists before the embedding column."""
    try:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    except Exception as exc:  # noqa: BLE001 — DBA may need to pre-provision
        op.execute("SELECT 1 FROM pg_extension WHERE extname = 'vector'")  # re-raise if truly absent
        print(f"CREATE EXTENSION skipped ({exc}); extension verified present.")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_policies',
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('data_classification', sa.String(length=16), nullable=False),
    sa.Column('allowed_model_classes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('allowed_providers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('external_allowed', sa.Boolean(), nullable=False),
    sa.Column('cost_budget_rs', sa.Float(), nullable=False),
    sa.Column('latency_budget_ms', sa.Integer(), nullable=False),
    sa.Column('fallback_rule', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_policies_organization_id'), 'ai_policies', ['organization_id'], unique=False)
    op.create_index('ix_ai_policy_lookup', 'ai_policies', ['capability', 'data_classification'], unique=False)
    op.create_table('ai_route_log',
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('data_classification', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('model_class', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('policy_ref', sa.String(length=80), nullable=True),
    sa.Column('reason_code', sa.String(length=60), nullable=False),
    sa.Column('fallback', sa.String(length=40), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_est_rs', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_route_log_organization_id'), 'ai_route_log', ['organization_id'], unique=False)
    op.create_index('ix_route_log_inv', 'ai_route_log', ['organization_id', 'investigation_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=60), nullable=False),
    sa.Column('object_id', sa.String(length=60), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('feedback_events',
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('feedback_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('effect', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_events_investigation_id'), 'feedback_events', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_feedback_events_organization_id'), 'feedback_events', ['organization_id'], unique=False)
    op.create_index('ix_feedback_org_inv', 'feedback_events', ['organization_id', 'investigation_id'], unique=False)
    op.create_table('historical_cases',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=False),
    sa.Column('kpi_code', sa.String(length=60), nullable=False),
    sa.Column('driver_class', sa.String(length=60), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('outcome_rs', sa.Float(), nullable=False),
    sa.Column('within_band', sa.Boolean(), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('access_roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analogue_for', sa.String(length=60), nullable=True),
    sa.Column('embedding', sa.JSON().with_variant(Vector(256), 'postgresql'), nullable=False),
    sa.Column('embedding_method', sa.String(length=40), nullable=False),
    sa.Column('embedding_version', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hist_cases_org_kpi', 'historical_cases', ['organization_id', 'kpi_code'], unique=False)
    op.create_index(op.f('ix_historical_cases_driver_class'), 'historical_cases', ['driver_class'], unique=False)
    op.create_index(op.f('ix_historical_cases_kpi_code'), 'historical_cases', ['kpi_code'], unique=False)
    op.create_index(op.f('ix_historical_cases_organization_id'), 'historical_cases', ['organization_id'], unique=False)
    op.create_table('impact_edges',
    sa.Column('parent_code', sa.String(length=60), nullable=False),
    sa.Column('child_code', sa.String(length=60), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('elasticity', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.Column('derivation_note', sa.Text(), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_edges_child_code'), 'impact_edges', ['child_code'], unique=False)
    op.create_index('ix_impact_edges_org_parent', 'impact_edges', ['organization_id', 'parent_code'], unique=False)
    op.create_index(op.f('ix_impact_edges_organization_id'), 'impact_edges', ['organization_id'], unique=False)
    op.create_index(op.f('ix_impact_edges_parent_code'), 'impact_edges', ['parent_code'], unique=False)
    op.create_table('impact_metrics',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('provenance', sa.String(length=120), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_impact_metrics_org_code', 'impact_metrics', ['organization_id', 'code'], unique=True)
    op.create_index(op.f('ix_impact_metrics_organization_id'), 'impact_metrics', ['organization_id'], unique=False)
    op.create_table('kpis',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_kpi_org_code')
    )
    op.create_index(op.f('ix_kpis_organization_id'), 'kpis', ['organization_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=False),
    sa.Column('active_scenario_id', sa.String(length=80), nullable=True),
    sa.Column('ai_cost_cap_rs', sa.Float(), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('pattern_reliability',
    sa.Column('pattern_class', sa.String(length=40), nullable=False),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('prior', sa.Float(), nullable=False),
    sa.Column('last_feedback_at', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_reliability_organization_id'), 'pattern_reliability', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pattern_reliability_pattern_class'), 'pattern_reliability', ['pattern_class'], unique=False)
    op.create_table('scenario_templates',
    sa.Column('scenario_id', sa.String(length=80), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=False),
    sa.Column('business_problem', sa.String(length=300), nullable=False),
    sa.Column('primary_kpi_code', sa.String(length=60), nullable=False),
    sa.Column('related_kpi_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('scenario_description', sa.Text(), nullable=False),
    sa.Column('source_configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('driver_configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('threshold_configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('materiality_configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('decision_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('guardrail_configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('persona_configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('entitlement_configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dataset_ref', sa.String(length=200), nullable=True),
    sa.Column('expected_outcome_ref', sa.String(length=200), nullable=True),
    sa.Column('demo_priority', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id')
    )
    op.create_index(op.f('ix_scenario_templates_organization_id'), 'scenario_templates', ['organization_id'], unique=False)
    op.create_table('source_systems',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('cadence', sa.String(length=20), nullable=False),
    sa.Column('grain', sa.String(length=120), nullable=False),
    sa.Column('publish_lag_days', sa.Integer(), nullable=False),
    sa.Column('data_classification', sa.String(length=20), nullable=False),
    sa.Column('lineage_note', sa.String(length=400), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_source_org_code')
    )
    op.create_index(op.f('ix_source_systems_organization_id'), 'source_systems', ['organization_id'], unique=False)
    op.create_table('stage_telemetry',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('stage_code', sa.String(length=40), nullable=False),
    sa.Column('method_label', sa.String(length=20), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('model_class', sa.String(length=40), nullable=True),
    sa.Column('route_reason', sa.String(length=60), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_est', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('cache_latency_saved_ms', sa.Integer(), nullable=False),
    sa.Column('cache_cost_avoided_rs', sa.Float(), nullable=False),
    sa.Column('confidence_impact', sa.Float(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_telemetry_organization_id'), 'stage_telemetry', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stage_telemetry_run_id'), 'stage_telemetry', ['run_id'], unique=False)
    op.create_index(op.f('ix_stage_telemetry_stage_code'), 'stage_telemetry', ['stage_code'], unique=False)
    op.create_table('evidence_records',
    sa.Column('doc_key', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('kpi_code', sa.String(length=40), nullable=False),
    sa.Column('driver_class', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('polarity', sa.String(length=16), nullable=False),
    sa.Column('support_weight', sa.Float(), nullable=False),
    sa.Column('contradiction_weight', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=False),
    sa.Column('occurred_at_days', sa.Integer(), nullable=False),
    sa.Column('data_classification', sa.String(length=16), nullable=False),
    sa.Column('access_roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('lineage', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('claims', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_key')
    )
    op.create_index('ix_evidence_kpi_driver', 'evidence_records', ['kpi_code', 'driver_class'], unique=False)
    op.create_index(op.f('ix_evidence_records_driver_class'), 'evidence_records', ['driver_class'], unique=False)
    op.create_index(op.f('ix_evidence_records_kpi_code'), 'evidence_records', ['kpi_code'], unique=False)
    op.create_index(op.f('ix_evidence_records_organization_id'), 'evidence_records', ['organization_id'], unique=False)
    op.create_table('kpi_observations',
    sa.Column('kpi_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('calendar_key', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('grain', sa.String(length=120), nullable=False),
    sa.Column('freshness_age_days', sa.Integer(), nullable=False),
    sa.Column('quality_state', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_observations_organization_id'), 'kpi_observations', ['organization_id'], unique=False)
    op.create_index('ix_obs_kpi_period', 'kpi_observations', ['kpi_id', 'period_key'], unique=False)
    op.create_index('ix_obs_source_period', 'kpi_observations', ['source_id', 'period_key'], unique=False)
    op.create_table('observation_facts',
    sa.Column('kpi_id', sa.String(length=36), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('baseline_period_key', sa.String(length=20), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('p0', sa.Float(), nullable=False),
    sa.Column('p1', sa.Float(), nullable=False),
    sa.Column('q0', sa.Float(), nullable=False),
    sa.Column('q1', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fact_kpi_period', 'observation_facts', ['kpi_id', 'period_key'], unique=False)
    op.create_index(op.f('ix_observation_facts_kpi_id'), 'observation_facts', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_observation_facts_organization_id'), 'observation_facts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_observation_facts_period_key'), 'observation_facts', ['period_key'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('region_scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('password_salt', sa.String(length=64), nullable=False),
    sa.Column('pbkdf2_iterations', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('kpi_contracts',
    sa.Column('kpi_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_definition', sa.Text(), nullable=False),
    sa.Column('formula_sql', sa.Text(), nullable=False),
    sa.Column('formula_note', sa.String(length=600), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('business_function', sa.String(length=80), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('owner_role', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('calendar_rule', sa.String(length=400), nullable=False),
    sa.Column('hierarchy_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'kpi_id', 'version', name='uq_contract_kpi_version')
    )
    op.create_index(op.f('ix_kpi_contracts_kpi_id'), 'kpi_contracts', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_kpi_contracts_organization_id'), 'kpi_contracts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_kpi_contracts_status'), 'kpi_contracts', ['status'], unique=False)
    op.create_table('contract_versions',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('changed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('change_reason', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_versions_contract_id'), 'contract_versions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_versions_organization_id'), 'contract_versions', ['organization_id'], unique=False)
    op.create_table('detection_results',
    sa.Column('kpi_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('source_value', sa.Float(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('ci_lo', sa.Float(), nullable=False),
    sa.Column('ci_hi', sa.Float(), nullable=False),
    sa.Column('deviation', sa.Float(), nullable=False),
    sa.Column('deviation_pct', sa.Float(), nullable=False),
    sa.Column('robust_z', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('statistical_significance', sa.Float(), nullable=False),
    sa.Column('history_n', sa.Integer(), nullable=False),
    sa.Column('cold_start_flag', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_results_kpi_id'), 'detection_results', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_detection_results_organization_id'), 'detection_results', ['organization_id'], unique=False)
    op.create_table('investigations',
    sa.Column('kpi_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('contract_version', sa.Integer(), nullable=False),
    sa.Column('workflow_state', sa.String(length=30), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('reliability_snapshot', sa.Float(), nullable=True),
    sa.Column('confidence_cap_snapshot', sa.Float(), nullable=True),
    sa.Column('working_value_snapshot', sa.Float(), nullable=True),
    sa.Column('cold_start_mode', sa.Boolean(), nullable=False),
    sa.Column('certainty_state', sa.String(length=30), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.Column('lead_margin', sa.Float(), nullable=True),
    sa.Column('certainty_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('abstention', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('clarification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigation_kpi_state', 'investigations', ['kpi_id', 'workflow_state'], unique=False)
    op.create_index(op.f('ix_investigations_kpi_id'), 'investigations', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_investigations_organization_id'), 'investigations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_investigations_workflow_state'), 'investigations', ['workflow_state'], unique=False)
    op.create_table('kpi_contract_drivers',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('driver_code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('prior_weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('hypothesis_class', sa.String(length=60), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_contract_drivers_contract_id'), 'kpi_contract_drivers', ['contract_id'], unique=False)
    op.create_table('kpi_contract_entitlements',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('row_scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('masked_columns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('domains', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_contract_entitlements_contract_id'), 'kpi_contract_entitlements', ['contract_id'], unique=False)
    op.create_table('kpi_contract_rights',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('action_class', sa.String(length=60), nullable=False),
    sa.Column('may_recommend', sa.Boolean(), nullable=False),
    sa.Column('may_simulate', sa.Boolean(), nullable=False),
    sa.Column('may_approve', sa.Boolean(), nullable=False),
    sa.Column('approve_limit_rs', sa.Float(), nullable=False),
    sa.Column('escalate_to_role', sa.String(length=40), nullable=True),
    sa.Column('scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_contract_rights_contract_id'), 'kpi_contract_rights', ['contract_id'], unique=False)
    op.create_table('kpi_contract_sources',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('source_system_id', sa.String(length=36), nullable=False),
    sa.Column('lineage_path', sa.String(length=400), nullable=False),
    sa.Column('is_authoritative', sa.Boolean(), nullable=False),
    sa.Column('expected_cadence', sa.String(length=20), nullable=False),
    sa.Column('expected_grain', sa.String(length=120), nullable=False),
    sa.Column('tolerance_pct', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_contract_sources_contract_id'), 'kpi_contract_sources', ['contract_id'], unique=False)
    op.create_table('kpi_contract_thresholds',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('expected_lo', sa.Float(), nullable=True),
    sa.Column('expected_hi', sa.Float(), nullable=True),
    sa.Column('warning_deviation_pct', sa.Float(), nullable=True),
    sa.Column('critical_deviation_pct', sa.Float(), nullable=True),
    sa.Column('exposure_rs_per_point', sa.Float(), nullable=False),
    sa.Column('margin_weight', sa.Float(), nullable=False),
    sa.Column('strategic_weight', sa.Float(), nullable=False),
    sa.Column('min_history', sa.Integer(), nullable=False),
    sa.Column('cold_start_flag', sa.Boolean(), nullable=False),
    sa.Column('floor_band', sa.String(length=20), nullable=True),
    sa.Column('quality_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_contract_thresholds_contract_id'), 'kpi_contract_thresholds', ['contract_id'], unique=True)
    op.create_table('kpi_relations',
    sa.Column('a_contract_id', sa.String(length=36), nullable=False),
    sa.Column('b_contract_id', sa.String(length=36), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('elasticity', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['a_contract_id'], ['kpi_contracts.id'], ),
    sa.ForeignKeyConstraint(['b_contract_id'], ['kpi_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_relations_a_contract_id'), 'kpi_relations', ['a_contract_id'], unique=False)
    op.create_index(op.f('ix_kpi_relations_b_contract_id'), 'kpi_relations', ['b_contract_id'], unique=False)
    op.create_index(op.f('ix_kpi_relations_organization_id'), 'kpi_relations', ['organization_id'], unique=False)
    op.create_table('proposed_contract_changes',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('proposed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('proposed_by_role', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('merged_to_version', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_org_contract', 'proposed_contract_changes', ['organization_id', 'contract_id'], unique=False)
    op.create_index(op.f('ix_proposed_contract_changes_contract_id'), 'proposed_contract_changes', ['contract_id'], unique=False)
    op.create_index(op.f('ix_proposed_contract_changes_organization_id'), 'proposed_contract_changes', ['organization_id'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('confidence_cap', sa.Float(), nullable=False),
    sa.Column('working_value', sa.Float(), nullable=False),
    sa.Column('working_source_id', sa.String(length=36), nullable=False),
    sa.Column('working_justification', sa.Text(), nullable=False),
    sa.Column('freshness_profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('penalties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=True),
    sa.Column('run_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_contract_id'), 'reconciliation_runs', ['contract_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_organization_id'), 'reconciliation_runs', ['organization_id'], unique=False)
    op.create_table('decision_collisions',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('option_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('option_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('affected_kpi', sa.String(length=60), nullable=False),
    sa.Column('combined_effect_pct', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('collision_type', sa.String(length=20), nullable=False),
    sa.Column('owners', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('combined_note', sa.Text(), nullable=True),
    sa.Column('resolution_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.String(length=30), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_role', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dec_collisions_inv', 'decision_collisions', ['organization_id', 'investigation_id'], unique=False)
    op.create_index(op.f('ix_decision_collisions_investigation_id'), 'decision_collisions', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_decision_collisions_organization_id'), 'decision_collisions', ['organization_id'], unique=False)
    op.create_table('decision_options',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('driver', sa.String(length=60), nullable=False),
    sa.Column('lever', sa.String(length=60), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('expected_impact_rs', sa.Float(), nullable=False),
    sa.Column('impact_lo_rs', sa.Float(), nullable=False),
    sa.Column('impact_hi_rs', sa.Float(), nullable=False),
    sa.Column('cost_rs', sa.Float(), nullable=False),
    sa.Column('cash_exposure_rs', sa.Float(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('owner_role', sa.String(length=40), nullable=False),
    sa.Column('simulation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('guardrail_status', sa.String(length=20), nullable=True),
    sa.Column('guardrail_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rights_verdict', sa.String(length=20), nullable=True),
    sa.Column('rights_note', sa.Text(), nullable=True),
    sa.Column('escalation_target', sa.String(length=40), nullable=True),
    sa.Column('comparable_to', sa.String(length=60), nullable=True),
    sa.Column('external_proposal', sa.Boolean(), nullable=False),
    sa.Column('decision_health', sa.String(length=30), nullable=True),
    sa.Column('evidence_set', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=True),
    sa.Column('simulation_version', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dec_options_inv', 'decision_options', ['organization_id', 'investigation_id'], unique=False)
    op.create_index(op.f('ix_decision_options_investigation_id'), 'decision_options', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_decision_options_organization_id'), 'decision_options', ['organization_id'], unique=False)
    op.create_table('decomposition_components',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_id', sa.String(length=36), nullable=False),
    sa.Column('component', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('query_ref', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decomp_inv', 'decomposition_components', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_decomposition_components_investigation_id'), 'decomposition_components', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_decomposition_components_kpi_id'), 'decomposition_components', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_decomposition_components_organization_id'), 'decomposition_components', ['organization_id'], unique=False)
    op.create_table('investigation_hypotheses',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('driver_code', sa.String(length=40), nullable=False),
    sa.Column('pattern_class', sa.String(length=40), nullable=False),
    sa.Column('support_mass', sa.Float(), nullable=False),
    sa.Column('contradiction_mass', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('freshness_avg', sa.Float(), nullable=False),
    sa.Column('source_agreement', sa.Float(), nullable=False),
    sa.Column('pattern_prior', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('final_confidence', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reasoning_path', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hyp_inv', 'investigation_hypotheses', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_hypotheses_investigation_id'), 'investigation_hypotheses', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_hypotheses_organization_id'), 'investigation_hypotheses', ['organization_id'], unique=False)
    op.create_table('investigation_stage_events',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('from_state', sa.String(length=30), nullable=False),
    sa.Column('to_state', sa.String(length=30), nullable=False),
    sa.Column('stage_code', sa.String(length=40), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('artifact_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_stage_events_investigation_id'), 'investigation_stage_events', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_stage_events_organization_id'), 'investigation_stage_events', ['organization_id'], unique=False)
    op.create_table('materiality_scores',
    sa.Column('detection_id', sa.String(length=36), nullable=False),
    sa.Column('kpi_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('significance', sa.Float(), nullable=False),
    sa.Column('exposure_rs', sa.Float(), nullable=False),
    sa.Column('margin_weight', sa.Float(), nullable=False),
    sa.Column('strategic_weight', sa.Float(), nullable=False),
    sa.Column('risk_factor', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=20), nullable=False),
    sa.Column('monitor_only', sa.Boolean(), nullable=False),
    sa.Column('arithmetic', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('threshold_comparison', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['kpi_contracts.id'], ),
    sa.ForeignKeyConstraint(['detection_id'], ['detection_results.id'], ),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiality_scores_detection_id'), 'materiality_scores', ['detection_id'], unique=False)
    op.create_index(op.f('ix_materiality_scores_kpi_id'), 'materiality_scores', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_materiality_scores_organization_id'), 'materiality_scores', ['organization_id'], unique=False)
    op.create_table('reconciliation_conflicts',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('source_a_id', sa.String(length=36), nullable=False),
    sa.Column('source_b_id', sa.String(length=36), nullable=True),
    sa.Column('value_a', sa.Float(), nullable=True),
    sa.Column('value_b', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('confidence_impact', sa.Float(), nullable=False),
    sa.Column('penalty', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('routed_to_user_id', sa.String(length=36), nullable=True),
    sa.Column('routed_role', sa.String(length=40), nullable=True),
    sa.Column('resolution_state', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_conflicts_organization_id'), 'reconciliation_conflicts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_conflicts_run_id'), 'reconciliation_conflicts', ['run_id'], unique=False)
    op.create_table('decision_records',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_role', sa.String(length=40), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_role', sa.String(length=40), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('monitoring_plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_set', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('guardrail_status', sa.String(length=20), nullable=True),
    sa.Column('rights_verdict', sa.String(length=20), nullable=True),
    sa.Column('simulation_version', sa.String(length=20), nullable=False),
    sa.Column('predicted_impact_rs', sa.Float(), nullable=True),
    sa.Column('actual_impact_rs', sa.Float(), nullable=True),
    sa.Column('outcome_variance', sa.Float(), nullable=True),
    sa.Column('within_band', sa.Boolean(), nullable=True),
    sa.Column('outcome_note', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['decision_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dec_records_inv', 'decision_records', ['organization_id', 'investigation_id'], unique=False)
    op.create_index(op.f('ix_decision_records_investigation_id'), 'decision_records', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_decision_records_option_id'), 'decision_records', ['option_id'], unique=False)
    op.create_index(op.f('ix_decision_records_organization_id'), 'decision_records', ['organization_id'], unique=False)
    op.create_table('hypothesis_evidence',
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_records.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['investigation_hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hev_hyp', 'hypothesis_evidence', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_evidence_evidence_id'), 'hypothesis_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_evidence_hypothesis_id'), 'hypothesis_evidence', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_evidence_investigation_id'), 'hypothesis_evidence', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_evidence_organization_id'), 'hypothesis_evidence', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypothesis_evidence_organization_id'), table_name='hypothesis_evidence')
    op.drop_index(op.f('ix_hypothesis_evidence_investigation_id'), table_name='hypothesis_evidence')
    op.drop_index(op.f('ix_hypothesis_evidence_hypothesis_id'), table_name='hypothesis_evidence')
    op.drop_index(op.f('ix_hypothesis_evidence_evidence_id'), table_name='hypothesis_evidence')
    op.drop_index('ix_hev_hyp', table_name='hypothesis_evidence')
    op.drop_table('hypothesis_evidence')
    op.drop_index(op.f('ix_decision_records_organization_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_option_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_investigation_id'), table_name='decision_records')
    op.drop_index('ix_dec_records_inv', table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_reconciliation_conflicts_run_id'), table_name='reconciliation_conflicts')
    op.drop_index(op.f('ix_reconciliation_conflicts_organization_id'), table_name='reconciliation_conflicts')
    op.drop_table('reconciliation_conflicts')
    op.drop_index(op.f('ix_materiality_scores_organization_id'), table_name='materiality_scores')
    op.drop_index(op.f('ix_materiality_scores_kpi_id'), table_name='materiality_scores')
    op.drop_index(op.f('ix_materiality_scores_detection_id'), table_name='materiality_scores')
    op.drop_table('materiality_scores')
    op.drop_index(op.f('ix_investigation_stage_events_organization_id'), table_name='investigation_stage_events')
    op.drop_index(op.f('ix_investigation_stage_events_investigation_id'), table_name='investigation_stage_events')
    op.drop_table('investigation_stage_events')
    op.drop_index(op.f('ix_investigation_hypotheses_organization_id'), table_name='investigation_hypotheses')
    op.drop_index(op.f('ix_investigation_hypotheses_investigation_id'), table_name='investigation_hypotheses')
    op.drop_index('ix_hyp_inv', table_name='investigation_hypotheses')
    op.drop_table('investigation_hypotheses')
    op.drop_index(op.f('ix_decomposition_components_organization_id'), table_name='decomposition_components')
    op.drop_index(op.f('ix_decomposition_components_kpi_id'), table_name='decomposition_components')
    op.drop_index(op.f('ix_decomposition_components_investigation_id'), table_name='decomposition_components')
    op.drop_index('ix_decomp_inv', table_name='decomposition_components')
    op.drop_table('decomposition_components')
    op.drop_index(op.f('ix_decision_options_organization_id'), table_name='decision_options')
    op.drop_index(op.f('ix_decision_options_investigation_id'), table_name='decision_options')
    op.drop_index('ix_dec_options_inv', table_name='decision_options')
    op.drop_table('decision_options')
    op.drop_index(op.f('ix_decision_collisions_organization_id'), table_name='decision_collisions')
    op.drop_index(op.f('ix_decision_collisions_investigation_id'), table_name='decision_collisions')
    op.drop_index('ix_dec_collisions_inv', table_name='decision_collisions')
    op.drop_table('decision_collisions')
    op.drop_index(op.f('ix_reconciliation_runs_organization_id'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_contract_id'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_proposed_contract_changes_organization_id'), table_name='proposed_contract_changes')
    op.drop_index(op.f('ix_proposed_contract_changes_contract_id'), table_name='proposed_contract_changes')
    op.drop_index('ix_proposals_org_contract', table_name='proposed_contract_changes')
    op.drop_table('proposed_contract_changes')
    op.drop_index(op.f('ix_kpi_relations_organization_id'), table_name='kpi_relations')
    op.drop_index(op.f('ix_kpi_relations_b_contract_id'), table_name='kpi_relations')
    op.drop_index(op.f('ix_kpi_relations_a_contract_id'), table_name='kpi_relations')
    op.drop_table('kpi_relations')
    op.drop_index(op.f('ix_kpi_contract_thresholds_contract_id'), table_name='kpi_contract_thresholds')
    op.drop_table('kpi_contract_thresholds')
    op.drop_index(op.f('ix_kpi_contract_sources_contract_id'), table_name='kpi_contract_sources')
    op.drop_table('kpi_contract_sources')
    op.drop_index(op.f('ix_kpi_contract_rights_contract_id'), table_name='kpi_contract_rights')
    op.drop_table('kpi_contract_rights')
    op.drop_index(op.f('ix_kpi_contract_entitlements_contract_id'), table_name='kpi_contract_entitlements')
    op.drop_table('kpi_contract_entitlements')
    op.drop_index(op.f('ix_kpi_contract_drivers_contract_id'), table_name='kpi_contract_drivers')
    op.drop_table('kpi_contract_drivers')
    op.drop_index(op.f('ix_investigations_workflow_state'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_organization_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_kpi_id'), table_name='investigations')
    op.drop_index('ix_investigation_kpi_state', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_detection_results_organization_id'), table_name='detection_results')
    op.drop_index(op.f('ix_detection_results_kpi_id'), table_name='detection_results')
    op.drop_table('detection_results')
    op.drop_index(op.f('ix_contract_versions_organization_id'), table_name='contract_versions')
    op.drop_index(op.f('ix_contract_versions_contract_id'), table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_index(op.f('ix_kpi_contracts_status'), table_name='kpi_contracts')
    op.drop_index(op.f('ix_kpi_contracts_organization_id'), table_name='kpi_contracts')
    op.drop_index(op.f('ix_kpi_contracts_kpi_id'), table_name='kpi_contracts')
    op.drop_table('kpi_contracts')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_observation_facts_period_key'), table_name='observation_facts')
    op.drop_index(op.f('ix_observation_facts_organization_id'), table_name='observation_facts')
    op.drop_index(op.f('ix_observation_facts_kpi_id'), table_name='observation_facts')
    op.drop_index('ix_fact_kpi_period', table_name='observation_facts')
    op.drop_table('observation_facts')
    op.drop_index('ix_obs_source_period', table_name='kpi_observations')
    op.drop_index('ix_obs_kpi_period', table_name='kpi_observations')
    op.drop_index(op.f('ix_kpi_observations_organization_id'), table_name='kpi_observations')
    op.drop_table('kpi_observations')
    op.drop_index(op.f('ix_evidence_records_organization_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_kpi_code'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_driver_class'), table_name='evidence_records')
    op.drop_index('ix_evidence_kpi_driver', table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_stage_telemetry_stage_code'), table_name='stage_telemetry')
    op.drop_index(op.f('ix_stage_telemetry_run_id'), table_name='stage_telemetry')
    op.drop_index(op.f('ix_stage_telemetry_organization_id'), table_name='stage_telemetry')
    op.drop_table('stage_telemetry')
    op.drop_index(op.f('ix_source_systems_organization_id'), table_name='source_systems')
    op.drop_table('source_systems')
    op.drop_index(op.f('ix_scenario_templates_organization_id'), table_name='scenario_templates')
    op.drop_table('scenario_templates')
    op.drop_index(op.f('ix_pattern_reliability_pattern_class'), table_name='pattern_reliability')
    op.drop_index(op.f('ix_pattern_reliability_organization_id'), table_name='pattern_reliability')
    op.drop_table('pattern_reliability')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_kpis_organization_id'), table_name='kpis')
    op.drop_table('kpis')
    op.drop_index(op.f('ix_impact_metrics_organization_id'), table_name='impact_metrics')
    op.drop_index('ix_impact_metrics_org_code', table_name='impact_metrics')
    op.drop_table('impact_metrics')
    op.drop_index(op.f('ix_impact_edges_parent_code'), table_name='impact_edges')
    op.drop_index(op.f('ix_impact_edges_organization_id'), table_name='impact_edges')
    op.drop_index('ix_impact_edges_org_parent', table_name='impact_edges')
    op.drop_index(op.f('ix_impact_edges_child_code'), table_name='impact_edges')
    op.drop_table('impact_edges')
    op.drop_index(op.f('ix_historical_cases_organization_id'), table_name='historical_cases')
    op.drop_index(op.f('ix_historical_cases_kpi_code'), table_name='historical_cases')
    op.drop_index(op.f('ix_historical_cases_driver_class'), table_name='historical_cases')
    op.drop_index('ix_hist_cases_org_kpi', table_name='historical_cases')
    op.drop_table('historical_cases')
    op.drop_index('ix_feedback_org_inv', table_name='feedback_events')
    op.drop_index(op.f('ix_feedback_events_organization_id'), table_name='feedback_events')
    op.drop_index(op.f('ix_feedback_events_investigation_id'), table_name='feedback_events')
    op.drop_table('feedback_events')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_route_log_inv', table_name='ai_route_log')
    op.drop_index(op.f('ix_ai_route_log_organization_id'), table_name='ai_route_log')
    op.drop_table('ai_route_log')
    op.drop_index('ix_ai_policy_lookup', table_name='ai_policies')
    op.drop_index(op.f('ix_ai_policies_organization_id'), table_name='ai_policies')
    op.drop_table('ai_policies')
    # ### end Alembic commands ###
